### ISSUE TITLE
Send function not working properly

### ISSUE THREAD

**Issue by carlotrimarchi** [mikehaertl/phpwkhtmltopdf#97] opened 2015-04-30 10:19 UTC
Hi,
I'm trying to generate pdf files in Codeigniter.

I set the library like this:

        $this->load->library('mypdf');
        $this->pdf = new Pdf;
        $options = array(
            'binary' => '/usr/local/bin/wkhtmltopdf'
        );
        $this->pdf->setOptions($options);
        $content = $this->load->view('pdf/test_new_pdf', '', true);
        $this->pdf->addPage($content);
        $this->pdf->send();
        $this->pdf->saveAs('./public/pdf/payment_requests/test.pdf');

I'm using the example code you posted in the documentation as content for the pdf, but when I try to generate a pdf on the browser the error message "Failed to load PDF document" appears. Both on Firefox and Chrome.
The pdf file, though, is generated.

I've found out that to make the "send" command to work I have to remove all the html tags between body, like this:

    <!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>

            This is an example header.
            Demo
            This is example content
            This is an example footer.

    </body>
    </html>

Any suggestions?
Thanks!

**Comment by carlotrimarchi** [comment] 2015-04-30 10:53
An update:

If I remove the <h1> tags from the html the send() function is actually working. It seems to be working fine with div and p tags. It also doesn't work when I try to add a font-family to the css.

**Comment by mikehaertl** [comment] 2015-04-30 10:56
There's not really any restriction on the HTML you can use. So either way, it should work. Have you checked for an error?

```
if (!$pdf->send()) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
}
```

Also if the file is sent, what is the content of the file? Can you send it for download (`$pdf->send('test.pdf')`) and see what the file contains? Sometimes this helps to find the error message.

**Comment by carlotrimarchi** [comment] 2015-04-30 12:30
Hey,
thanks for the answer.

Here's a generated pdf:

**Comment by mikehaertl** [comment] 2015-04-30 12:53
I don't see any PDF file. Also, please first try for yourself if you can open it e.g. in a text editor. I'm not here to do the debugging for you ;)

**Comment by carlotrimarchi** [comment] 2015-04-30 13:07
Sorry, I replied by email attaching the file and it doesn't work on github. I can only attacch images, so here's a link to the pdf:

https://dl.dropboxusercontent.com/u/189424/test2.pdf

I opened it with an editor but I couldn't understand what's wrong

**Comment by mikehaertl** [comment] 2015-04-30 13:12
If i open this document, the first line contains the `wkhtmltopdf` command that was used to create the PDF. This line should not be there.

```
/usr/local/bin/wkhtmltopdf '/private/var/tmp/tmp_wkhtmlto_pdf_xxS2mv.html' '/private/var/tmp/tmp_wkhtmlto_pdf_PTNWf8.pdf'%PDF-1.4                                                                                                                         
1 0 obj                                                                                                                      
<<                                                                                                                           
/Title (þÿ)                                                                                                                  
/Creator (þÿ^@w^@k^@h^@t^@m^@l^@t^@o^@p^@d^@f^@ ^@0^@.^@1^@2^@.^@2^@.^@1)                                                    
/Producer (þÿ^@Q^@t^@ ^@4^@.^@8^@.^@6)                                                                                       
/CreationDate (D:20150430142646+02'00')                                                                                      
>>                 
```

So you must echo this out somewhere from your PHP script.

**Comment by carlotrimarchi** [comment] 2015-05-04 11:17
Well, I figured out that the problem was with a webfont failing to load.

Still, other weird stuff keeps happening. You're right saying that that line should not be there, but that line is somehow added when the `send` command fails. For example, now I noticed that this character `&quot;` is causing the error. The pdf gets created correctly with the `saveAs` command (opening with the text editor I don't see that line), but if I use `send` it's the same issue again. And it is the same exact code.

**Comment by mikehaertl** [comment] 2015-05-04 15:06
If the generation fails, then what do you expect? It  will always send some erroneous file in this case. You should make sure, that the command does not fail first.

I'm using the `send()` method, too and it works fine for me.

**Comment by carlotrimarchi** [comment] 2015-05-04 16:23
The generation doesn't fail. 
The ´saveAs()` method outputs a perfectly working pdf file. 
The `send()` method, on the other hand, outputs a corrupted pdf which I can't even open.

**Comment by mikehaertl** [comment] 2015-05-04 16:41
Still I can not see, how this should happen. Do you combine both in one request? If you do: What if you just use `send()` without `saveAs()`?

**Comment by julienchepa** [comment] 2015-05-06 15:22
Hi,

I have the same issue when i'm throwing exception I just have : 

Could not create PDF: Failed without error message: wkhtmltopdf 'https://url.local/pdf/view-pdf' '/private/var/folders/f4/lf9rty4n47vglq0xfjgqvfmh0000gn/T/tmp_wkhtmlto_pdf_6GtIHS.pdf'

When i'm trying the command in the shell, it works well. 
I'm using send() function in Laravel 5.

That's weird because I could use and worked perfectly it before.

Any idea ? 

Thanks in advance.

**Comment by mikehaertl** [comment] 2015-05-06 16:24
> That's weird because I could use and worked perfectly it before.

What do you mean by "before"? What did you change?

**Comment by julienchepa** [comment] 2015-05-06 16:48
I couldn't explain what I changed. 
I worked on something else when I did it well.

I tried to use saveAs() function but it didn't work as well.

**Comment by mikehaertl** [comment] 2015-05-06 16:51
@julienchepa I don't think that your problem is related. My guess is that it's because of this weird looking URL that you use: ` 'https://url.local/pdf/view-pdf'`.

**Comment by julienchepa** [comment] 2015-05-06 16:54
@mikehaertl I just hiding the right URL but this URL return me the right view.

Do you think HTTPS could be a issue ?

**Comment by mikehaertl** [comment] 2015-05-06 16:56
I simply don't know. This library just executes the `wkhtmltopdf` command. If that doesn't work, it's a problem with wkhtmltopdf.

**Comment by julienchepa** [comment] 2015-05-06 16:59
Okay, I'll try to solve it but thank you anyway for your help.

**Comment by mikehaertl** [comment] 2015-06-04 10:04
Quoting a comment by @zealfire:

> I tried to debug and I am facing this warning:
>
>Warning: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\project\core\vendor\mikehaertl\php-tmpfile\src\File.php:77) in mikehaertl\tmp\File->send() (line 69 of C:\xampp\htdocs\project\core\vendor\mikehaertl\php-tmpfile\src\File.php)

>Line 77 says this: readfile($this->_fileName);

> Update: I modified the line where it says: header('Content-Length: '.filesize($this->_fileName)); and made it as comments and my problem got solved. Can you explain why?Is this problem faced by me only or it has happened previously too. According to me $this->_fileName is outputting the content beforehand which is causing a problem.

**Comment by mikehaertl** [comment] 2015-06-04 10:16
@zealfire: This code is actually an exact copy of an example from the PHP manual, see here:

http://php.net/manual/en/function.readfile.php

It's weird that it works without. I remember that Apache adds this header back in automatically in some situations. Maybe you can verify this in your browser? Try once with and without that line and see, if the `Content-Length` header is still there.

**Comment by zealfire** [comment] 2015-06-04 13:29
I previously forgot to tell you that this time pdf is rendering inline but the warning has still not suppressed.Also I don't see any Content-Length header when I have removed it(obviously) and when I am added that in the code I face this message "Failed to load PDF document".Any way to remove the warning .Btw when I am using these lines:

if (!$this->pdfGenerator->send()) {
    throw new Exception('Could not create PDF: '.$this->pdfGenerator->getError());
}

the warning is being generated.Thanks.

**Comment by mikehaertl** [comment] 2015-06-04 14:30
@zealfire Just to verify that you really have the same issue as @carlotrimarchi : Does `saveAs()` work for you?

**Comment by zealfire** [comment] 2015-06-04 22:14
Yes saveAs() works for me too.

**Comment by zealfire** [comment] 2015-06-29 08:06
@mikehaertl  hi, lately I have been trying to generate pdf from html but face this error:

`Failed without error message: C://"Program Files"/wkhtmltopdf/bin/wkhtmltopdf.exe --page-size "A4" --orientation "portrait" "C:\Users\sony\AppData\Local\Temp\tmpDF52.tmp.html" "C:\Users\sony\AppData\Local\Temp\tmpDF72.tmp.pdf"`

Can  you give me a hint as to why this error can arise or a way to debug this? Thanks.

**Comment by mikehaertl** [comment] 2015-06-29 08:37
@zealfire I've removed your comment as it was not related to this issue. Please open a new issue if you think there's something wrong.

**Comment by mikehaertl** [comment] 2015-06-29 17:46
I've just [undone](https://github.com/mikehaertl/php-shellcommand/commit/89c0682ca739b5989df34abfb6cc35abe58ef038) a [change](https://github.com/mikehaertl/php-shellcommand/commit/9355d4f7a87bc4ecee5cdee24de389374d2594f3) in https://github.com/mikehaertl/php-shellcommand, which was reported in #111 to cause a similar issue.

So could you please try to update `mikehaertl/php-shellcommand`? Latest version is 1.0.6:

```
composer update mikehaertl/php-shellcommand
```

**Comment by zealfire** [comment] 2015-06-29 20:17
@mikehaertl thanks for looking into issue for me previous error message has gone but I am now facing this problem:

`Loading pages (1/6) [> ] 0% [======> ] 10% [========> ] 14% [=========> ] 16% [==================> ] 30% [============================================================] 100% Counting pages (2/6) [============================================================] Object 1 of 1 Resolving links (4/6) [============================================================] Object 1 of 1 Loading headers and footers (5/6) Printing pages (6/6) [> ] Preparing [============================================================] Page 1 of 1 Done Exit with code 1 due to network error: ContentOperationNotPermittedError`

**Comment by zealfire** [comment] 2015-06-29 21:21
@mikehaertl  On further investigation I came to conclusion that inclusion of base tag in head section oh html was cause of problem. In the head section I was writing a code like this:

<base href=" \path\to\file" \>
which was causing Exit with code 1 due to network error: ContentOperationNotPermittedError but after removing it the error was removed. Any reasons for this?

**Comment by mikehaertl** [comment] 2015-07-01 07:07
@carlotrimarchi Please let me know if the `send()` problem is still relevant for you.

@zealfire I have no idea and the problem is probably more on the side of `wkhtmltopdf`, not my library.

**Comment by mikehaertl** [comment] 2015-08-10 18:45
As there was no further feedback and I could not reproduce the issue, I'm closing this now.

**Closed by mikehaertl** 2015-08-10 18:45 UTC

**Comment by rahulmangal1990** [comment] 2017-02-03 06:51
Hello when i genrate pdf using  wkhtmltopdf some time working well. but sometime

 while (true)
                    {
                        var read =  p.StandardOutput.BaseStream.Read(buffer, 0, buffer.Length);

                        if (read <= 0)
                        {
                            break;
                        }
                        ms.Write(buffer, 0, read);
                    }
p.StandardOutput.BaseStream.Read not reading html from html file. give some error like task was cancelled..?
