### ISSUE TITLE
Centos Linux - No create the file from php

### ISSUE THREAD

**Issue by juliogtz** [mikehaertl/phpwkhtmltopdf#139] opened 2015-11-26 00:43 UTC
Hi Mike.
Just having some trouble with wkhtmltopdf. It works fine in command line but in PHP I keep without any pdf file: sh: . 

This is the current configuration: phpwkhtmltopdf - latest version CentOS 

Do you have any idea, why is working good in Command Line and fail from php script?

Thanks.

**Comment by juliogtz** [comment] 2015-11-26 00:51
Code:

	error_reporting(E_ALL);
	require '../vendor/autoload.php';
	use mikehaertl\wkhtmlto\Pdf;



	$options = array("binary" => "/usr/local/bin/wkhtmltopdf", 'encoding' => 'UTF-8');
	$pdf = new Pdf($options);
	$pdf->addPage('<html>hola</html>');



	if (!$pdf->saveAs('../porfa.pdf')) {
    throw new Exception('Could not create PDF -- SAVE: '.$pdf->getError());
	}


	$content = $pdf->toString();
	if ($content === false) {
	    throw new Exception('Could not create PDF: '.$pdf->getError());
	}

ERROR:

Fatal error: Uncaught exception 'Exception' with message 'Could not create PDF -- SAVE: Loading pages (1/6) [> ] 0% [======> ] 10%' in /index.php:36 Stack trace: #0 {main} thrown in /index.php on line 36

**Comment by mikehaertl** [comment] 2015-11-26 07:57
This is a duplicate of #125.

**Closed** 2015-12-12 10:15 UTC
