### ISSUE TITLE
Webfont URWGeometric not rendered at all in pdf

### ISSUE THREAD

**Issue by siddiqlm** [mikehaertl/phpwkhtmltopdf#343] opened 2020-01-08 04:22 UTC
I am generating pdf using 'wkhtmltopdf' and with this module. I am using a custom web font called 'URWGeometric". The page looks good in the browser. But when generating as pdf the font is not rendered with the web font. Instead, the pdf generated with the default font. 

```
@font-face {font-family: 'URWGeometric-Regular';src: url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_3_0.eot');src: url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_3_0.eot?#iefix') format('embedded-opentype'),url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_3_0.woff2') format('woff2'),url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_3_0.woff') format('woff'),url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_3_0.ttf') format('truetype');}
@font-face {font-family: 'URWGeometric-Medium';src: url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_4_0.eot');src: url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_4_0.eot?#iefix') format('embedded-opentype'),url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_4_0.woff2') format('woff2'),url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_4_0.woff') format('woff'),url('../../fonts/MyFontsWebfontsKit/webfonts/3464D4_4_0.ttf') format('truetype');}
```

I tried 
1. Generating base64code from ttf file and included that in the CSS
2. Included the website URL instead of relative path in the CSS
3. Installed the font on windows using otf. 

Nothing worked so far. Any idea how to resolve this issue?

**Comment by mikehaertl** [comment] 2020-01-08 07:03
Does it work with `wkthmltopdf` on the command line? If not, then you should better report this over there.

**Comment by mikehaertl** [comment] 2020-01-13 14:40
Closing as there was no further feedback and the issue is probably not related to this library.

**Closed by mikehaertl** 2020-01-13 14:40 UTC
