### ISSUE TITLE
`footer-html` key doesn't works in setOptions

### ISSUE THREAD

**Issue by zealfire** [mikehaertl/phpwkhtmltopdf#119] opened 2015-08-01 17:18 UTC
Hi, I was trying to generate footer in the PDF by setting `footer-html` key provided by wkhtmltopdf library. I am using a code similar to given below
`$pdf->setOptions(array('footer-html' => <html><h1>Hello</h1><h2>world</h2></html>'));`
but the problem is the html footer is not being rendered in the final PDF generated. Can you tell me what am I doing wrong? Can this key be set in the wrapper. Thanks.

**Comment by mikehaertl** [comment] 2015-08-01 17:52
It should work. Sometimes the footer is not visible due to HTML / CSS layout issues. Apart from that I can't really do much here. You could show me the generated final wkhtmltopdf command:

```
$pdf->saveAs(...);
echo (string) $pdf->getCommand();
```

**Comment by zealfire** [comment] 2015-08-01 21:02
@mikehaertl  sorry I was gave wrong information regarding generated PDF. PDF is being generated but with no content. Also when I am simply writing:
`$pdf->setOptions(array('footer-html' => <html>Hello world</html>'));` the code works and PDF  is being generated successfully.

**Comment by mikehaertl** [comment] 2015-08-02 09:27
What is the output of `$pdf->getError()` after you generated the PDF?

**Comment by mikehaertl** [comment] 2015-08-10 18:50
I'm closing this for now as there was no further feedback. If you still feel there's something to fix, please provide a full simplified example to reproduce the problem.

**Closed by mikehaertl** 2015-08-10 18:50 UTC
