### ISSUE TITLE
PDF Generation hangs on OSX

### ISSUE THREAD

**Issue by lkb2k** [mikehaertl/phpwkhtmltopdf#85] opened 2015-01-08 19:07 UTC
I'm able to get it to work fine on linux, but when i try to use phpwkhtmltopdf on OS X, the wkhtmltopdf process just hangs and never finishes.

If i copy/paste the command I see running in the process list, it executes fine and generates the PDF, but if i hit my PHP file through the browser, the wkhtmltopdf command never completes.

**Comment by mikehaertl** [comment] 2015-01-09 08:31
I don't have OS X so it's very hard for me to supply help. You could try the workaround described here:

https://github.com/mikehaertl/phpwkhtmltopdf/issues/56#issuecomment-61456283

**Comment by MrRootUp** [comment] 2015-02-18 14:36
I have the exact same problem but on a windows server 2008 (don't ask...). I've found out that the temporary HTML and PDF files both gets correctly generated but when stream_get_contents gets called everything hangs. I assume there is some kind of deadlock happening between php and wkhtmltopdf.exe. 

Anyway I settled with replacing stream_get_contents(inside the Command class) with file_get_contents and everything worked fine then.

**Comment by mikehaertl** [comment] 2015-02-18 16:04
@MrRootUp Did you try the workaround I've linke above?

**Comment by MrRootUp** [comment] 2015-02-19 08:57
@mikehaertl I just tried it and it works perfectly. The strange thing is that proc_open version does work with most html files while **certain html files** always hangs the process. Anyway I'll stick to the workaround since there seems to be several problems with proc_open on windows.

On a side note moving proc_close above the stream_get_contents also worked.

**Comment by mikehaertl** [comment] 2015-02-19 09:21
AS tivie pointet out in the other thread, there are some problems with `proc_open()` on windows, e.g. https://bugs.php.net/bug.php?id=51800. Not sure, why your workaround helps, but it probably will simply cut off some data from the stream, so I don't want to change that (it's not really logical anyway).

I will close this issue for now, as you confirmed that the solution with `'useExec' => true' works.

**Closed by mikehaertl** 2015-02-19 09:21 UTC
