### ISSUE TITLE
Footer and Header not working

### ISSUE THREAD

**Issue by psmith104** [mikehaertl/phpwkhtmltopdf#51] opened 2014-06-05 18:32 UTC
When I try to add a footer using this code nothing shows up.
```
$footer = "<html><div style='height:2.54cm;width:100%;background:#cccccc;'>Hello how are you<br/>hhhh<br/>hhhh</div></html>";
$pdf->addPage($top.$specHtml.$modelHtml.$picHtml, array('footer-html' => $footer));
```
Everything else is generated fine.
When I use the same code but with header-html it show a small white space at the top of my pages but no other content is inserted.

**Comment by cerpnjaki** [comment] 2015-07-01 13:06
$pdf = new Pdf(array(        
                'header-html' => getcwd().'/footer.html',
                'footer-html' => getcwd().'/footer.html',
            ));    

why is this not working mikehaertl?

**Comment by mikehaertl** [comment] 2015-07-01 13:11
@cerpnjaki Does it work on the commandline with raw `wkhtmltopdf`? And what is `$pdf->getError()`?

**Comment by cerpnjaki** [comment] 2015-07-01 13:26
mikehaertl tnx for you comment.

$pdf = new Pdf(array(        
                     'no-outline',
                    'margin-bottom' => '5cm',
                    'footer-html' => 'http://www.google.com'
    
            ));    
            $pdf->addPage('<!DOCTYPE html>somehtml</html>');

            if(!$pdf->send()) {
                echo "Error: ".$pdf->getError();
                die;
            }


---
i tried twice: onetime with this parameter: 'no-outline', <- i get error as it is down
second time without 'no-outline', parameter. <- i do not get error and i do no get pdf 

this is my error message:

Error: Unknown long argument --no-outline Name: wkhtmltopdf 0.9.9 Synopsis: wkhtmltopdf [OPTIONS]...  [More input files] Description: Converts one or more HTML pages into a PDF document, *not* using wkhtmltopdf patched qt. General Options: --collate Collate when printing multiple copies --copies Number of copies to print into the pdf file (default 1) --extended-help Display more extensive help, detailing less common command switches -h, --help Display help -O, --orientation Set orientation to Landscape or Portrait -s, --page-size Set paper size to: A4, Letter, etc. --password HTTP Authentication password -p, --proxy Use a proxy -q, --quiet Be less verbose --username HTTP Authentication username -V, --version Output version information an exit Reduced Functionality: This version of wkhtmltopdf has been compiled against a version of QT without the wkhtmltopdf patches. Therefore some features are missing, if you need these features please use the static version. Currently the list of features only supported with patch QT includes: * Printing more then one HTML document into a PDF file. * Running without an X11 server. * Adding a document outline to the PDF file. * Adding headers and footers to the PDF file. * Generating a table of contents. * Adding links in the generated PDF file. * Printing using the screen media-type. * Disabling the smart shrink feature of webkit. Contact: If you experience bugs or want to request new features please visit , if you have any problems or comments please feel free to contact me: see

**Comment by mikehaertl** [comment] 2015-07-01 13:28
Well, you try to use an option that is not supported by your `wkhtmltopdf` version:

> Unknown long argument --no-outline Name: wkhtmltopdf 0.9.9 

So you should upgrade to a newer version or - if you already have it somewhere - set the full path to that file in the `binary` option.

**Comment by mikehaertl** [comment] 2015-07-01 13:30
Also better avoid the google page as test. Their site is probably a bit more complex than it looks. Better try with a local header/footer file first.

**Comment by cerpnjaki** [comment] 2015-07-01 13:39
ok mikehaertl, i will try and give you feedback! tnx for your realy fast replies!
LG, Igor

**Comment by mikehaertl** [comment] 2015-07-02 07:40
I'm closing this issue for now as the problem of OP is with `wkhtmltopdf`, not with this library.

**Closed by mikehaertl** 2015-07-02 07:40 UTC

**Comment by Dyktus** [comment] 2016-10-26 09:55
I had simillar problems and I want to left some notes here. 
Official documentation of wkhtmltopdf says that header and footer options are only available using patched QT and I didn't have patched QT.

I found instruction of installation this right here and now everything works:
http://stackoverflow.com/questions/35617491/how-to-install-wkhtmltopdf-patched-qt-without-compiling

**Comment by rawaby88** [comment] 2016-12-24 15:54
the problem is about css float. try to remove it and render the pdf again

**Comment by cristian100** [comment] 2017-08-31 12:36
If testing with --header-html option, make sure you include the following as part of your string:

`<!DOCTYPE html>`


Once I added that, it works flawless in both wkhtmltopdf in command line or using phpwkhtmltopdf
