### ISSUE TITLE
Header / Footer on each page

### ISSUE THREAD

**Issue by salacis** [mikehaertl/phpwkhtmltopdf#173] opened 2016-06-18 01:44 UTC
Anyway how to add an header and footer on each page?
Sorry if this has been asked before.

**Comment by MikeVelazcoMtz** [comment] 2016-06-18 02:07
I was just about to ask for this!! :laughing:

**Comment by MikeVelazcoMtz** [comment] 2016-06-18 02:57
I have good new @salacis, it's possible to add headers and footer:
>$aConfig = array(
>		'footer-html' => 'your_header.html'
>	);
> $pdf = new Pdf($aConfig);
>
>$pdf->addPage("tests/{yourPrincipalFileName}.html");

I'm having problems with the integration, but you need to check the documentation. In your terminal type:

`wkhtmltopdf -H`

Theorically you can use all of the possible arguments from the documentation.

**Comment by mikehaertl** [comment] 2016-06-18 09:09
I'm closing this, as it's not a bug. Please carefully read this section again:

https://github.com/mikehaertl/phpwkhtmltopdf#setting-options

Especially the feature *global options*. Make sure, you study `wkhtmltopdf -H`. This library is only a frontend so I will not repeat the `wkhtmltopdf` documentation here.

**Closed by mikehaertl** 2016-06-18 09:09 UTC
