### ISSUE TITLE
Corrupted PDF

### ISSUE THREAD

**Issue by CorentinMic** [mikehaertl/phpwkhtmltopdf#270] opened 2018-04-03 08:54 UTC
Hi, 
I have correctly installed wkhtmltopdf (0.12.4) on my debian server and generating a pdf of https://example.com/ is working in command line.
When I try the same thing in PHP I'm getting a corrupted PDF.
I tried putting my own HMTL to generate a PDF file and it's working but only under few conditions : 

- PDF is corrupted if my content need more than one page to display 

- PDF is corrupted if content is too long. In my case, I have a only 4 titles (h tags) and it seems that if there is more than X letters the PDF is corrupted.  

When PDF is corrupted, no error is sent by PHP, only an error is prompted by the browser or pdf reader.

**Comment by mikehaertl** [comment] 2018-04-03 09:09
Can you come up with a minimal example to reproduce the issue?

Also did you try to set `useExec` to `true` (https://github.com/mikehaertl/phpwkhtmltopdf#wrapper-options)?  If this helps, could you do me a favour and check if this change makes it work without `useExec`: https://github.com/mikehaertl/php-shellcommand/pull/27/files. You just have to manually change the file in your vendor directory.

**Comment by CorentinMic** [comment] 2018-04-03 09:28
I generate some titles in php and it's working : 
![image](https://user-images.githubusercontent.com/8841730/38241185-de837f3a-3731-11e8-9edc-d8b40ed3255d.png)

If I add some text like : `'<p>Test</p>'`, it doesn't work.

Here is my pdf code : 
```
$pdf = new Pdf(array(
		'ignoreWarnings' => true,
		'commandOptions' => array(
			'useExec' => true,      // Can help if generation fails without a useful error message
			'procEnv' => array(
				// Check the output of 'locale' on your system to find supported languages
				'LANG' => 'en_US.utf-8',
			),
		),
		'encoding' => 'UTF-8',
		'page-size' => 'A4',
		'orientation portrait',
		'dpi' => '96',
		'disable-smart-shrinking',
		'quiet'
	));
	$pdf->binary = '/usr/local/bin/wkhtmltopdf';
	$pdf->addPage('<html>'.$pdfContent.'</html>'); //Where $pdfContent is my HTML content

	if (!$pdf->send()) {
		echo $pdf->getError();
	}
```

**Comment by mikehaertl** [comment] 2018-04-03 09:32
Thanks, can you also paste the example HTML that breaks?

**Comment by CorentinMic** [comment] 2018-04-03 09:45
Here is the HTML : 
```
<html>
   <h1>1. Gestion des candidats</h1>
   <h2>1.1 Fichier recrutement</h2>
   <h3>1.1.1 Fiche de traitement validée par Jacques Martiny le 20/03/2018</h3>
   <h4>1.1.1.1 Information sur le traitement</h4>
   <p>Test</p>
</html>
```

**Comment by mikehaertl** [comment] 2018-04-03 10:08
I've tested your example but can't reproduce the problem.

As we already had many similar reports I really want to finally figure out, what's going on here. But as long as I don't have the issue I can't do much. Maybe you can do some tests **without** our library but with raw PHP. It's not very hard. All that this library does, is to call the `wkhtmltopdf` binary with `proc_open()`. The relevant code to execute the command is here: https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L338. You only have to copy and modify a couple of lines.

Then I would create a static HTML file and first feed this into `wkhtmltopdf` on the command line. If this works, I'd try to run the command via `proc_open()` and try to make it break. If it suddenly works, maybe you can further debug our php-shellcommand library.

Please report back your results.

**Comment by CorentinMic** [comment] 2018-04-03 12:07
I'm afraid I don't have the time to do that right now but I will keep in touch if I do later.
Thank you for your support anyway !

**Comment by CorentinMic** [comment] 2018-04-03 16:33
After several hours of debugging, my collegue and I have finally find out the problem ! It comes from these lines (79 to 82 in File.php) :
```
$isIOS = preg_match('/i(phone|pad|pod)/i', $_SERVER['HTTP_USER_AGENT']);
      if (!$isIOS) {
            header('Content-Length: '.filesize($this->_fileName));
        }
```
When you remove the Content-length header, the pdf finally display correctly.
Hope it will help you ! :)

**Comment by mikehaertl** [comment] 2018-04-03 16:50
Awesome, thanks for putting so much effort into the issue. But to be honest I wonder, how those lines could be a problem. The `Content-Length` header is recommended as it informs the browser about the size of the file to download. 

Maybe it has to do with [this](https://stackoverflow.com/a/2429162/767752) answer that I found on SO:

> I would like to stress this: if your browser doesn't appear to be obeying the headers generated by your PHP script—especially Content-Length—it is fairly likely that Apache's mod_deflate extension is enabled.

So do you maybe have this extension enabled? Or another module that compresses the output? And what exactly was the error you see in the browser? If this is causing issues we definitely need to fix this in https://github.com/mikehaertl/php-tmpfile

**Comment by CorentinMic** [comment] 2018-04-04 07:15
You're right, the mod_deflate extension in enabled on my server ! 
So what would be the best solution ? Adding a parameter to your project to disable this header ? I think commenting the line in the vendor directory is not a perfect solution. 
Or you let users disable the mod_deflate extension on those specific pages.
Anyway this problem should probably appear in the documentation. :)

**Comment by mikehaertl** [comment] 2018-04-04 07:47
Ok, I will consider adding an option to php-tmpfile. But I think the better approach is to disable mod_deflate for your specific download URL in your Apache configuration (i.e. set `no-gzip` [env](http://httpd.apache.org/docs/2.2/env.html#special) variable). Something like this:

    SetEnvIfNoCase REQUEST_URI ^/pdf.php$ no-gzip dont-vary

Removing the `Content-Length` header has the drawback, that you no longer see a progress bar when you download larger files in the browser. I would not recommend that.

Can you test the above configuration and report back if it fixes the issue for you? Then I'll add a note to the README.

**Comment by CorentinMic** [comment] 2018-04-06 15:17
Hi ! 
I tried to set up an .htaccess file (with differents commands to deactivate compression) but it seems that I couldn't achieve to do that. I do not master at all the htaccess configuration and I bet my commands were not right. So I disabled mod_deflate on the server to check but even if the module was deactivated, I still had the error when generating the pdf. Maybe this is not the reason of the error.

**Comment by mikehaertl** [comment] 2018-04-06 16:56
Ok, thanks for trying. I will leave this issue open for now. Maybe I (or someone else?) find some time to dive deeper into the problem. To me `mod_deflate` still sound like the most reasonable explanation.

**Comment by CreoCoding** [comment] 2018-11-23 17:12
I am having a similar issue. Tried commenting out the header code in the File.php. Also have been playing with the .htaccess file to disable deflate for .pdf but doesn't seem to make a difference.

**Comment by CreoCoding** [comment] 2018-12-02 16:41
FYI I had the same issue happen using mPDF (which I didn't notice this website already had installed), which I am also looking there for a solution - and this was just creating a file with '<h1>Hi</h1>'. But because 2 different PDF generators are having issues it leads me to believe it HAS to be the server in some way so the deflate or something else.

**Comment by asolopovas** [comment] 2019-07-09 13:44
I am having similar issue. If I generate pdf using command line in windows 10 using my test server it works without a problem. If I try to do the same via plugin it generates emty pdf. I put together repo you can test it. https://github.com/asolopovas/phpwkhtmltest

**Comment by howardgrigg** [comment] 2020-03-02 00:56
Hi Mike, I was having this same issue. Basically it would work to save the pdf but not send it to the browser. It would send an empty file (correctly named but corrupted) or a blank screen on the browser. 

I added the line you posted above to my .htaccess file:
```
SetEnvIfNoCase REQUEST_URI ^/pdf.php$ no-gzip dont-vary
```
And now it works perfectly for multipage relatively complicated pdfs. Thanks!

**Comment by mikehaertl** [comment] 2021-03-25 07:34
I've  added a note to the README about how to deal with the content-length problem. This should help with the issues discussed here. So closing this for now.

**Closed by mikehaertl** 2021-03-25 07:34 UTC
