### ISSUE TITLE
Error with HTTPS files

### ISSUE THREAD

**Issue by babeuloula** [mikehaertl/phpwkhtmltopdf#142] opened 2015-12-14 10:26 UTC
Hi, 

I try to render some charts with Highcharts and the scripts url are https://code.highcharts.com/highcharts.js and https://code.highcharts.com/modules/funnel.js

```html
<html lang="fr">

    <head>

        <meta charset="UTF-8">
        <meta http-equiv="content-language" content="fr">

        <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

        <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
        <script type="text/javascript" src="https://code.highcharts.com/modules/funnel.js"></script>

        <style>
            * {
                -webkit-box-shadow  : none !important;
                -moz-box-shadow     : none !important;
                -ms-box-shadow      : none !important;
                -o-box-shadow       : none !important;
                box-shadow          : none !important;

                -webkit-text-shadow : none !important;
                -moz-text-shadow    : none !important;
                -ms-text-shadow     : none !important;
                -o-text-shadow      : none !important;
                text-shadow         : none !important;

                color               : #000;
            }

            body {
                background-color: #FFF;
                overflow: visible;
            }
        </style>

    </head>

    <body>

           MY_CONTENT

    </body>

</html>
```

```
Fatal error: Uncaught exception 'Exception' with message 'Could not create PDF: Loading pages (1/6)
[>                                                           ] 0%
[======>                                                     ] 10%
[======>                                                     ] 11%
[================>                                           ] 28%
[======================>                                     ] 37%
```

You have any solution ?

Thanks

**Comment by mikehaertl** [comment] 2015-12-14 10:29
This is probably a duplicate of #125. Does it work with raw `wkhtmltopdf` on the command line?

**Comment by babeuloula** [comment] 2015-12-14 10:35
Probably. I will try, how I can get the command ? Because I have some pages  to render.

**Comment by mikehaertl** [comment] 2015-12-14 10:43
You can't really get the command as it will use some temporary files on disk. If you only need the arguments, try `echo (string)$pdf->getCommand()`. But it's better to try with a simple static HTML file instead.

**Comment by babeuloula** [comment] 2015-12-14 10:54
Its works with the command line.

And I tried on a VM with Ubuntu 14.04.3 and its works with your plugin. My server is a CentOS 6.6. I do not know why the PDF does not render ...

**Comment by mikehaertl** [comment] 2015-12-14 12:22
Ok, I'm closing this as duplicate of #125. Unfortunately we don't have a solution yet. Maybe check the discussion there and add a message if you find out more.

**Closed by mikehaertl** 2015-12-14 12:22 UTC
