### ISSUE TITLE
Could not create PDF: Failed without error message

### ISSUE THREAD

**Issue by craned** [mikehaertl/phpwkhtmltopdf#99] opened 2015-05-12 16:35 UTC
It appears that no matter what I do, I cannot create a pdf at all, and there is no error or warning to give any hint as to what's wrong.

    $pdf = new Pdf;
    $pdf->addPage('http://www.google.com');
    if (!$pdf->saveAs('temp.pdf')) {
        throw new \Exception('Could not create PDF: '.$pdf->getError());
    }

This produces the following:
        Could not create PDF: Failed without error message: wkhtmltopdf 'http://www.google.com' '/private/var/tmp/tmp_wkhtmlto_pdf_kThRYi.pdf' 

I can run this no problem from the command line so I'm not sure what I'm doing wrong. I don't know why it's creating a random pdf within /private/var/.

I am using Symfony, and it is using version "^2.0"

Thanks

**Comment by mikehaertl** [comment] 2015-05-13 08:21
That random file is OK, it's deleted after the PDF was downloaded or saved. Can you check if there's maybe some output on stdout: `echo $pdf->getCommand()->getOutput()`? If you're on Windows, you can also try to set the `useExec` feature (see [here](https://github.com/mikehaertl/phpwkhtmltopdf/issues/56#issuecomment-61456283))

**Comment by mikehaertl** [comment] 2015-05-13 08:24
Oh, and please also try with a local file first. It seems, that there are frequent issues with remote URLs, especially if it's making heavy use of js like google.com.

**Comment by hiroju** [comment] 2015-05-13 13:42
hi
i have same issue my develop enviroment is below

OS: centos 6.6(64bit)
framework: fuelphp 1.8 
useExec:false

my problem is caused by SElinux
so, i tryied to temporaly disabled SElinux , everything works fine
```setenforce 0```
this command is used for temporaly situation so if linux is restart, SElinux is enabled again

**Comment by hiroju** [comment] 2015-05-13 14:09
i have same issue
my develop enviroment is below
OS: CentOS 6.6 (64bit)
framework: fuelphp 1.8
useExec: false

myproblem is caused by SELinux
if SElinux is enabled, apache somtime cant create files

so, i tried to temporarily disable SElinux, everything works fine

please see this
http://stackoverflow.com/questions/4216596/php-function-is-executable-returns-false-even-though-the-file-is-definitely-exec/6986511#6986511

**Comment by mikehaertl** [comment] 2015-05-13 14:27
> if SElinux is enabled, apache sometime cant create any files

Now this is taking us somewhere - thanks for that hint!

@craned Can you check if it's the same issue for you?

If that's the case, it's nothing we can fix here. We may add a hint to the README, though.

**Comment by martindevnow** [comment] 2015-05-21 18:35
I was getting the error. It turns out the error was that wkhtmltopdf: command not found.
So, I changed it to execute wkhtmltopdf by providing the full path to wkhtmltopdf

Hope this helps anyone who might run into the same error.

**Comment by craned** [comment] 2015-05-26 21:36
@mikehaertl Sorry it took so long for me to respond. It's a shame you assumed my issue was the same as @hiroju. I'm on Mac so I don't believe SElinux is an issue. My apache logs don't show any errors. KnpSnappyBundle successfully creates a pdf when given the same html locally generated; it's just slightly blurry for some reason. Does your library automatically assume wkhtmltopdf is located in '/usr/local/bin/wkhtmltopdf'?

**Comment by hiroju** [comment] 2015-05-27 05:48
@craned yes, my wkhtmltopdf is located in '/usr/local/bin/wkhtmltopdf' (but it's in vagrant)
http://gyazo.com/f4f9acb14c52d7781863c63f90620a44

i'm using mac too. your situation is similar to my situation

at first, i tried to work my product with apache on mac but it didn't work well（only commandline works）
i don't know why only commandline work. offcorse, useExec was enabled.
i thought this is caused by something depend on mac

so i build centos with vagrant on mac and i disabled selinux
and then wkhtmltopdf is worked

**Comment by mikehaertl** [comment] 2015-05-27 07:23
> Does your library automatically assume wkhtmltopdf is located in '/usr/local/bin/wkhtmltopdf'?

It assumes, that `wkhtmltopdf` is in your `$PATH`. You can still configure the correct path in the `binary` option.

What I would try:

 1. Create a very simple PHP test script (without any of my libraries)
 2. There you build a simple `wkhtmltopdf` command string manually
 3. Execute that command with the same core code as this library that you find [here](https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L275) and [here](https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php#L284)

So simplify as much as possible until you find the point where it works / does not work anymore. Then report back...

**Comment by chunhui2001** [comment] 2015-05-30 06:46
Hello mikehaertl ,

I have same issues! And I dont's know how to fix!
Failed without error message: wkhtmltopdf '/tmp/tmp_wkhtmlto_pdf_1GWPn6.html' '/tmp/tmp_wkhtmlto_pdf_4WR1vN.pdf'

I had disabled SELinux SELinux status: disabled, But never resolved! My OS Environment is :
OS: CentOS release 6.6
wkhtmltopdf version: 0.12.2.1
nginx version: nginx/1.6.3

Could you help me for this problem?

And also Could you please help have a look this quesionts: http://stackoverflow.com/questions/30542462/wkhtmltopdf-0-12-2-1-php-exec-xvfb-run-error-xauth-command-not-found?noredirect=1#comment49158073_30542462

It puzzle me for a long time!!!

Thanks,
-Chunhui

**Comment by lexakozakov** [comment] 2015-06-11 20:19
I have the same issue with "/tmp" files on the CentOS server. On my macbook everything is OK.

**Comment by hiniesta** [comment] 2015-06-15 09:30
I have the same issue also in CentOS 6.6. Only works from cli. I have tried to set up other tmpDir, but have the same issue.
Thanks!

**Comment by lexakozakov** [comment] 2015-06-15 09:34
@hiniesta   It's not about directory permissions. /tmp has 0777 and available for each app on the server. 

Check out the next article. It helped me - https://jaimegris.wordpress.com/2015/03/04/how-to-install-wkhtmltopdf-in-centos-7-0/

**Comment by hiniesta** [comment] 2015-06-15 09:44
Thanks @lexakozakov . Not sure about that. I have solved it buy using exec.

Thanks!

**Comment by craned** [comment] 2015-06-17 19:27
I solved it by using the library, knp snappy bundle, instead. There was no fighting. Default pdf creation options can be set in the config.yml file. It worked great.

**Comment by mikehaertl** [comment] 2015-06-18 10:56
@craned Sorry that we couldn't solve the issue here, but glad that you found a working alternative solution. But maybe you could still let me know, if you also use CentOS.

**Comment by craned** [comment] 2015-06-18 18:28
My PHP tests did not include CentOS. Just Mac. It would have all needed to work with CentOS, but it never got that far.

**Comment by mikehaertl** [comment] 2015-06-29 17:46
I've just [undone](https://github.com/mikehaertl/php-shellcommand/commit/89c0682ca739b5989df34abfb6cc35abe58ef038) a [change](https://github.com/mikehaertl/php-shellcommand/commit/9355d4f7a87bc4ecee5cdee24de389374d2594f3) in https://github.com/mikehaertl/php-shellcommand, which was reported in #111 to cause a similar issue.

So could you please try to update `mikehaertl/php-shellcommand`? Latest version is 1.0.6:

```
composer update mikehaertl/php-shellcommand
```

**Comment by mikehaertl** [comment] 2015-08-10 18:48
I'm closing this now as there was no further feedback.

As noted above the issue was probably caused by some security settings on the above systems.

**Closed by mikehaertl** 2015-08-10 18:48 UTC

**Comment by charlie-lk** [comment] 2015-09-01 11:37
I have the same issue. Here is my test code.

<?php

require_once __DIR__.'/../vendor/autoload.php';

use mikehaertl\wkhtmlto\Pdf;

// You can pass a filename, a HTML string or an URL to the constructor
$pdf = new Pdf('<html><head></head><body>Hello pdf</body></html>');

// On some systems you may have to set the binary path.
 $pdf->binary = 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe';

if (!$pdf->saveAs('/user/page.pdf')) {
    echo $pdf->getError();
}

?>

**Comment by cyrrill** [comment] 2015-12-11 06:01
On Linux this issue may appear if you haven't before installed the wkhtmltopdf binary.

It would be useful if the error message could reflect that rather than exiting with no message. I would think checking for the command existence would be a basic sanity check?

**Comment by mikehaertl** [comment] 2015-12-11 07:25
@cyrrill Agreed. That's an issue for https://github.com/mikehaertl/php-shellcommand thouh.

**Comment by cyrrill** [comment] 2015-12-11 08:21
Hello @mikehaertl, I think adding something like this would fix it:

https://github.com/cyrrill/php-shellcommand/commit/9b838f1062d5f365d65b1ab19a4fecd560c6096b

I just wrote this commit directly on the github editor so I haven't tested it. Let me know if you like that approach and I'll send a PR in.

**Comment by alpacin0** [comment] 2015-12-18 16:40
I was facing the same problem running on Windows and Apache with same error message, I fixed the issue just a few minutes ago, by using 'bypass_shell' => 'true'; on the commandOptions and also specifying the binary path pointing to your installed wkhtmltopdf folder, normally in Program Files. 

Working code:

$pdf = new Pdf([
    'commandOptions' => [
        'useExec' => false,
                'escapeArgs' => false,
        'procOptions' => array(
            // This will bypass the cmd.exe which seems to be recommended on Windows
            'bypass_shell' => true,
            // Also worth a try if you get unexplainable errors
            'suppress_errors' => true,
        ),
    ],
]);
$globalOptions = array(
    'no-outline',         // Make Chrome not complain
    // Default page options
    'page-size' => 'Letter'
);

$pdf->setOptions($globalOptions);
$pdf->addPage('http://www.google.com');
$pdf->binary = 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe';
if (!$pdf->send()) {
    throw new Exception('Could not create PDF: '.$pdf->getError());
} 

If you set the useExec command parameter to true, then in your binary path you should add double quotes to "Program Files" or you will get the error C:\Program is not recognized as an internal or external command, operable program or batch file .. Thanks to Mikehaertl for the appreciated solution and amazing work with wkhtmltopdf. Cheers my friend.

**Comment by devil1591** [comment] 2016-11-28 15:50
Hi! 
I had the same problem, you need to install [VC13](https://www.microsoft.com/fr-fr/download/details.aspx?id=40784) on your server.

**Comment by rsplsk** [comment] 2017-03-17 03:28
Dear Mikehaert,
I have install pdftk and it server on windows machine.

I have configured your package into Laravel :- https://github.com/mikehaertl/php-pdftk

Now I am getting error when I am calling below code.
$pdf = new Pdf(public_path('files').'\form.pdf');
$pdf->fillForm(array(
        'name'=>'Sunil',
        'email' => 'sunil@mailinator.com',
    ))
    ->needAppearances()
    ->saveAs(public_path('files').'\filled.pdf');


Error: Failed to Open form data file.  

pdftk A="F:\php7xampp\htdocs\blog\public\files\form.pdf" fill_form "C:\Users\sunil.kansodiya\AppData\Local\Temp\php6058.tmp.xfdf" output "C:\Users\sunil.kansodiya\AppData\Local\Temp\tmp6059.tmp.pdf" drop_xfa need_appearances


This lib will work on Windows10 or other latest linux version also?

Can you please help me, I am waiting for your response?

Thanks Sunik

**Comment by mikesoule** [comment] 2018-10-02 21:46
If you landed here because you are using `php-fpm` and getting `xauth command not found`, here is how to solve it.

In `/etc/php-fpm.d` (on most Linux systems), add or update a `.conf` file with the following contents, where at least one of the paths contains each of the following: `which`, `xvfb-run`, and `xauth`.
```
[www]

env[PATH] = /usr/local/bin:/usr/bin:/bin
```

**Comment by zaidITpro** [comment] 2019-07-12 08:49
Can anyone tell me how to create the image and save it using wkhtmltoImage.

What I am trying to do is this.. from the documentation [https://github.com/mikehaertl/phpwkhtmltopdf](https://github.com/mikehaertl/phpwkhtmltopdf)

`$img = new Image('<div class='dds'>This is the code</div>");
 $Img->saveAs($path);
`
