### ISSUE TITLE
PDF downloads OK but corrupted in Adobe and Chrome

### ISSUE THREAD

**Issue by CreoCoding** [mikehaertl/phpwkhtmltopdf#298] opened 2018-11-21 23:02 UTC
using send it downloads the PDF without a problem and I can view it using preview (mac). But opening in Chrome or Adobe gives a corrupted error. 

Not sure what is causing it, I don't see any other errors anywhere.

**Comment by mikehaertl** [comment] 2018-11-22 06:11
Same as #270?

**Comment by mikehaertl** [comment] 2018-11-23 17:51
@CreoCoding Unfortunately I can't provide more help. So you'll have to play around a little, try what works and what doesn't - and what's the difference. There's not so much that can go wrong.

**Comment by CreoCoding** [comment] 2018-11-23 19:01
OK I will keep trying stuff and report what I find.

**Comment by Laeborg** [comment] 2019-04-24 12:15
I have experienced troubles with corrupted PDFs in Chrome as well and came across this thread.
In my case it was caused by some HTML in the top of the generated PDF file, which Chrome didn't like but Firefox just ignored.

Example:
`<div class="wrapper"><div class="morehtml"></div></div>
%PDF-1.4
1 0 obj
<<
/Title (˛ˇ)
/Creator (˛ˇwkhtmltopdf 0.12.5)
/Producer (˛ˇQt 4.8.7)
/CreationDate (D:20190423130048+02'00')
>>
endobj
3 0 obj
<<
/Type /ExtGState
/SA true
/SM 0.02
/ca 1.0
/CA 1.0
/AIS false
/SMask /None>>
endobj`

The website is this case is running Drupal 7 and the problem seemed to be that I tried to generate the PDF in a node template, like this:
`ob_start();

require('path/to/pdf-template.php');

$content = ob_get_clean();

$pdf->addPage($content, array(
            'viewport-size' => '1024x768'
));`

My solution was to generate the PDF in a custom module instead, with no preloaded HTML.

**Comment by mikehaertl** [comment] 2019-05-08 08:02
I'm closing this for now as there was no further feedback and there's also no clear example to reproduce the issue. The last comment also indicated a usage mistake (echo HTML before sending the file).

**Closed by mikehaertl** 2019-05-08 08:02 UTC
