### ISSUE TITLE
Problems for printing UTF-8 characters on footer/ header

### ISSUE THREAD

**Issue by newpen** [mikehaertl/phpwkhtmltopdf#108] opened 2015-06-23 09:19 UTC
I am now generating PDF with Chinese characters on both its header and footer:

``` 
$title = '中文字';

$options = array(		
		'encoding' => 'UTF-8',  // option with argument
		'header-left' => $title,		
		'footer-html' => 'footer.html',		
		'replace' => array(
			'title' =>$title
		),
	);
```	

Currently, the header can print out the characters fine, but for the footer, that I include an external html file for it and pass it through `replace`, the characters printed out becomes unrecognizable.

I already have 
`<meta content="text/html;charset=utf-8" http-equiv="Content-Type">`
`<meta content="utf-8" http-equiv="encoding">` 
inside the head tag of my footer.html file. How can I solve this? Thank you very much.

**Comment by mikehaertl** [comment] 2015-06-23 09:38
Again: Did you try this on the command line with a raw `wkhtmltopdf` command? Does it work there?

**Comment by isaiasfsilva** [comment] 2015-07-02 13:33
Hi, I have a similar problem! I use CentOS 7 and when a try on command line works perfectly. But when I use by PHP (phpwkhtmltopdf) the no-ascii characters do not show. 

Example: 'footer-left' =>'Página [page] de [toPage]', 'encoding'=>'UTF-8'

Result: 'Pgina 1 de 2'
Expected result: 'Página 1 de 2'

My version is 2.1.0
 
Thank you very much!

**Comment by mikehaertl** [comment] 2015-07-03 11:44
Had no time to reproduce yet. But this is rather a problem of https://github.com/mikehaertl/php-shellcommand.

I've opened the above issue there. What could work: pass a `LANG` environment variable to `proc_open`:

```
$pdf = new Pdf([
    'commandOptions' => [
        'procEnv' => [
            'LANG' => 'en_US.utf-8',
        ],
    ],
]);
```

**Comment by isaiasfsilva** [comment] 2015-07-03 11:48
Wow! It's working!
Thank you very much!

**Comment by mikehaertl** [comment] 2015-07-03 11:49
Ok. Did you use the same `LANG` value as above? This may vary, depending on the locales you have on your system. 

I try to add something to the README about this.

**Comment by isaiasfsilva** [comment] 2015-07-03 11:52
Do not. I used pt_BR.utf-8.

oks!

**Comment by mikehaertl** [comment] 2015-07-03 12:07
Updated the README.

@newpen Please let me know, if this also fixes the problem for you.

**Comment by newpen** [comment] 2015-07-03 13:03
@mikehaertl No it doesn't fix it..
But probably it isn't the problem of this. I tied the command line just now and the issue still exists.

**Comment by mikehaertl** [comment] 2015-07-03 17:22
@newpen 

1. Are you sure, you used the right value for `LANG`? You can check it on console with `env | grep LANG`. If it still doesn't work, maybe also try to set some other variables from `env` that contain something like `UTF-8`. I'm not sure, which variables are used by `wkhtmltopdf`.
2. Does the generated command string contain the right characters? You can get it with `echo (string) $pdf->getCommand()`. But of course make sure, that your page is able to serve UTF-8 correctly.

**Comment by newpen** [comment] 2015-07-06 02:39
@mikehaertl 

1. I chekced and the console showed en_US.UTF-8 using ` env | grep LANG `. I used the value but it didn't help.
2. The command string does contain the right UTF-8 characters when I print it out on my browser.

Thanks.

**Comment by mikehaertl** [comment] 2015-07-06 08:44
@newpen Can you try adding this line somewhere on top of your script:

```
setlocale(LC_CTYPE, "en_US.UTF-8");
```

I could reproduce the issue and this fixed it. I will try to include this in https://github.com/mikehaertl/php-shellcommand.

**Comment by newpen** [comment] 2015-07-07 02:38
@mikehaertl just tried that, it's still not showing correctly...

**Comment by mikehaertl** [comment] 2015-07-07 07:16
@newpen Are you on Windows? If so then please check this page for available locale strings:

https://msdn.microsoft.com/en-us/library/39cwe7zf(v=vs.90).aspx

You can also check the return value of `setlocale()`. If it is `false`, the locale is not supported by your system:

```
$val = setlocale(LC_CTYPE, "en_US.UTF-8");
var_dump($val);
```

**Comment by newpen** [comment] 2015-07-07 07:23
@mikehaertl No. I am using it on a Ubuntu VM.
vardump($val) returns `string(11) "en_US.UTF-8" `

**Comment by mikehaertl** [comment] 2015-07-07 07:43
@newpen Hmm. I'm running out of ideas. Actually your problem is not related to `setlocale()`, otherwhise you'd not see the correct characters in the browser, when you dump the command (this was the case for me and fixed by the right `setlocale()` setting).

Just to make sure, you do not use the `useExec` option in `commandOptions` or something? Because that would not make use of `procEnv` setting.

**Comment by newpen** [comment] 2015-07-07 08:05
@mikehaertl , no I didn;t use  'useExec'.
Actually my case may be different from @isaiasfsilva .
I just tried to use his characters but my result is 'PÃ​Â¡gina 1 de 2' rather than 'Pgina 1 de 2'

**Comment by mikehaertl** [comment] 2015-07-07 08:06
@newpen Are you sure, this is not a charset issue in the PDF? I tried this example:

```
<?php
include 'vendor/autoload.php';

use mikehaertl\wkhtmlto\Pdf;

$title = '中文字äüp';
$pdf = new Pdf(array(
    'encoding' => 'UTF-8',
    'header-left' => $title,
    'commandOptions' => array(
        'locale' => 'de_DE.utf-8',
        'procEnv' => array(
            'LANG' => 'de_DE.utf-8',
        ),
    ),
));
$pdf->addPage(__DIR__.'/test.html');
$pdf->saveAs('/tmp/test.pdf');

die($pdf->getCommand());
```

`test.html` only contains `<h1>Testcontent</h1>`. If I run the above, it outputs the correct `wkhtmltopdf command:

```
wkhtmltopdf --encoding 'UTF-8' --header-left '中文字äüp' '/www/dev.m-h-it.de/htdocs/pdf/test.html' out.pdf
```

The generated `out.pdf` does not contain the chinese characters. So it doesn't work with raw `wkthmtltopdf` either. This usually happens if the charset in the PDF does not contain the relevant characters.

Can you please try on the command line?

**Comment by newpen** [comment] 2015-07-07 08:14
@mikehaertl , I can print out the Chinese characters correctly. In fact, all the content in my PDF is Chinese, and they are printed out fine. My header and footer are also Chinese, and they also can be printed correctly using the way that you used. But once I included the external footer.html instead of the usual `--footer-left `, it all went wrong...

**Comment by mikehaertl** [comment] 2015-07-07 08:18
@newpen The question we have to solve is really: Is this a problem of `wkhtmltopdf` or `phpwkhtmltopdf`.

So what happens on the command line, if you use `--footer-html`?

**Comment by newpen** [comment] 2015-07-07 08:23
@mikehaertl, I guess it's more likely to be a problem of ` wkhtmltopdf `. Seems on the command line there is still issue when using ` --footer-html `. 

I think you can close the issue. Thanks.

**Comment by mikehaertl** [comment] 2015-07-07 08:34
Agreed. But thanks anyway, you helped to find an issue with utf-8 arguments (https://github.com/mikehaertl/php-shellcommand/issues/7).

**Closed by mikehaertl** 2015-07-07 08:34 UTC
